version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecomgo-app
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=ecomgo_user
      - MYSQL_PASSWORD=ecomgo_password
      - MYSQL_DATABASE=EcomGo
    networks:
      - ecomgo_network
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always

  db:
    image: mysql:8.0
    container_name: ecomgo-db
    environment:
      - MYSQL_ROOT_PASSWORD=ecomgo_password
      - MYSQL_DATABASE=EcomGo
      - MYSQL_USER=ecomgo_user
      - MYSQL_PASSWORD=ecomgo_password
    networks:
      - ecomgo_network
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

networks:
  ecomgo_network:
    driver: bridge

volumes:
  db_data:
    driver: local
