version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_USER=ecomgo_user
      - DB_PWD=ecomgo_password
      - DB_NAME=EcomGo
      - DB_PORT=3306
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: EcomGo
      MYSQL_USER: ecomgo_user
      MYSQL_PASSWORD: ecomgo_password
    ports:
      - "3306:3306"